user/urls.py
from django.conf.urls import patterns, url
from user.views import *


urlpatterns = patterns('',
    url(r'^$', user_info, name="user_info"),
    url(r'^match_list/$', match_list, name="match_list"),
    url(r'^match_list/(?P<match_id>\d+)/call_status/$', status, name="call_status"),
    url(r'^match_list/(?P<match_id>\d+)/receive_status/$', status, name="receive_status"),
    url(r'^match_list/(?P<match_id>\d+)/complete_status/$', status, name="complete_status"),

    url(r'^match_list/(?P<match_id>\d+)/call_status/cancel/$', cancel_guide, name="call_cancel"),
    url(r'^match_list/(?P<match_id>\d+)/receive_status/cancel/$', cancel_guide, name="receive_cancel"),

    url(r'^match_list/(?P<match_id>\d+)/receive_status/accept/$', accept_guide, name="receive_accept"),

    url(r'^match_list/(?P<match_id>\d+)/call_status/complete/$', complete_guide, name="call_complete"),
    url(r'^match_list/(?P<match_id>\d+)/receive_status/complete/$', complete_guide, name="receive_complete"),

    url(r'^match_list/(?P<match_id>\d+)/complete_status/review/$', review, name="review"),
)

user/forms.py
import re
from django import forms
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.forms.widgets import Textarea
from django.http.response import HttpResponseBadRequest
from rest_framework.status import HTTP_400_BAD_REQUEST
from travel.models import DefaultStation
from user.models import User

options_place = []
options_place.append((0, 'No Guide'))
for station in DefaultStation.objects.all().exclude(line__in=['E', 'G', 'I', 'S', 'SU', 'U']).order_by('station'):
    options_place.append((station.station_code, station))

options_language = []
options_language.append(('0', '한국어'))
options_language.append(('1', 'English'))
options_language.append(('2', '日本語'))
options_language.append(('3', '中国'))


options_gender = []
options_gender.append(('0', 'Man'))
options_gender.append(('1', 'Woman'))


error_message = {
    'min_max': {
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
        'max_length': 'less than %(limit_value)d characters. (current %(show_value)d)',
    },
    'about_me': {
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
        'max_length': 'less than %(limit_value)d characters. (current %(show_value)d)',
    },
    'username': {
        'required': 'Please enter ID.',
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
        'max_length': 'less than %(limit_value)d characters. (current %(show_value)d)',
    },
    'password': {
        'required': 'Please enter password',
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
    },
    'placeLanguage': {
        'invalid_choice': 'Please enter correct choice.',
        'invalid_list': 'Please enter correct list.'
    },
    'email': {
        'required': 'Missing email address.',
    },
    'cert_code': {
        'required': 'Enter correct Code.'
    },
    'invalid_login': 'Please enter correct ID/ PW',
}


class Clean:
    @staticmethod
    def _username(username):
        if not re.search(r'^[A-Za-z1-9_]+$', username):
            raise forms.ValidationError('Username is Alphabet, underline(_) and Number only.')

    @staticmethod
    def exist_username(username):
        Clean._username(username)
        try:
            User.objects.get(username=username)
        except (ObjectDoesNotExist, MultipleObjectsReturned):
            return username
        raise forms.ValidationError("")

    @staticmethod
    def not_exist_username(username):
        Clean._username(username)
        try:
            User.objects.get(username=username)
        except (ObjectDoesNotExist, MultipleObjectsReturned):
            raise forms.ValidationError("User info doesn't exist.")
        return username

    @staticmethod
    def not_exist_email(email):
        try:
            User.objects.filter(email=email)
        except ObjectDoesNotExist:
            raise forms.ValidationError("User info doesn't exist.")
        return email

    @staticmethod
    def password_check(password, password_check):
        if password == password_check:
            return password_check

        raise forms.ValidationError('Check password again.')

    @staticmethod
    def name(name):
        if name != '':
            compiler = re.compile(r'^[A-Za-zㄱ-ㅣ가-힣]+')
            if compiler.findall(name):
                if name != compiler.findall(name)[0]:
                    raise forms.ValidationError('User name - Alphabet and Hangeul only.')
            else:
                raise forms.ValidationError('User name - Alphabet and Hangeul only.')
        return name

    @staticmethod
    def content(content):
        if content != '':
            compiler = re.compile(r'^[0-9A-Za-zㄱ-ㅣ가-힣]+')
            if compiler.findall(content):
                pass
            else:
                raise forms.ValidationError('Alphabet, Hangeul and Number only.')
        return content


class SendForm(forms.Form):
    username = forms.CharField(label='ID', min_length=4, max_length=30, required=True,
                               error_messages=error_message['username'])
    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])

    def clean_username(self):
        return Clean.not_exist_username(self.cleaned_data['username'])

    def clean_email(self):
        return Clean.not_exist_email(self.cleaned_data['email'])


class LostForm(forms.Form):
    username = forms.CharField(label='ID', min_length=4, max_length=30, required=True,
                               error_messages=error_message['username'])
    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])
    cert_code = forms.CharField(label='Code', max_length=30, required=True,
                                error_messages=error_message['cert_code'])
    password = forms.CharField(label="Password", min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput, error_messages=error_message['password'])
    password_check = forms.CharField(label="Password(again)", min_length=6, max_length=30, required=True,
                                     widget=forms.PasswordInput, error_messages=error_message['password'])

    def clean_username(self):
        return Clean.not_exist_username(self.cleaned_data['username'])

    def clean_email(self):
        return Clean.not_exist_email(self.cleaned_data['email'])

    def clean_password_check(self):
        return Clean.password_check(self.cleaned_data['password'], self.cleaned_data['password_check'])


class SignupForm(forms.Form):
    username = forms.CharField(label='ID', min_length=4, max_length=30, required=True,
                               error_messages=error_message['username'])
    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])
    password = forms.CharField(label="Password", min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput, error_messages=error_message['password'])
    password_check = forms.CharField(label="Password(again)", min_length=6, max_length=30, required=True,
                                     widget=forms.PasswordInput, error_messages=error_message['password'])

    def clean_password_check(self):
        return Clean.password_check(self.cleaned_data['password'], self.cleaned_data['password_check'])

    def clean_username(self):
        return Clean.exist_username(self.cleaned_data['username'])


class UserInfoForm(forms.Form):
    profile_picture = forms.ImageField(widget=forms.FileInput, required=False)
    first_name = forms.CharField(label="First_Name", min_length=1, max_length=30, required=False,
                                 error_messages=error_message['min_max'])
    last_name = forms.CharField(label="Last_Name", min_length=1, max_length=30, required=False,
                                error_messages=error_message['min_max'])
    gender = forms.ChoiceField(label='Gender', choices=options_gender, required=False)
    place = forms.MultipleChoiceField(label='Place', widget=forms.SelectMultiple, choices=options_place,
                                      required=False, error_messages=error_message['placeLanguage'])
    language = forms.MultipleChoiceField(label='Language', widget=forms.SelectMultiple, choices=options_language,
                                         required=False, error_messages=error_message['placeLanguage'])
    about_me = forms.CharField(label='About_Me', max_length=300, required=False,
                               widget=Textarea, error_messages=error_message['about_me'])

    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])
    password = forms.CharField(label="Password(current)", min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput, error_messages=error_message['password'])
    change_password = forms.CharField(label="Password(change)", min_length=6, max_length=30, required=False,
                                      widget=forms.PasswordInput, error_messages=error_message['password'])
    change_password_check = forms.CharField(label="Password(change again)", min_length=6, max_length=30,
                                            required=False, widget=forms.PasswordInput,
                                            error_messages=error_message['password'])

    def clean_first_name(self):
        return Clean.name(self.cleaned_data['first_name'])

    def clean_last_name(self):
        return Clean.name(self.cleaned_data['last_name'])

    def clean_change_password_check(self):
        return Clean.password_check(self.cleaned_data['change_password'], self.cleaned_data['change_password_check'])


class ReviewForm(forms.Form):
    content = forms.CharField(label='About_Me', min_length=1, max_length=300, required=True,
                              widget=Textarea, error_messages=error_message['about_me'])

    def clean_content(self):
        return Clean.content(self.cleaned_data['content'])

templates/base.html
<!DOCTYPE HTML>
<!--//
This web page has been developed by J.
 - jicjjang12@gmail.com
-->
<html lang="ko">
<head>
    <title>Show me the Seoul</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <link rel="shortcut icon" type="image/ico" href="/static/img/favicon.ico" />

    <!--[if lt IE 9]>
    <script src="/static/vendor/html5shiv/dist/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}{% endblock %}

    <!--[if lt IE 9]>
    <script src="/static/vendor/respond/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    {% block nav %}{% endblock %}

    {% block content-prev %}{% endblock %}

    <div class="container container-main">
        {% block content %}{% endblock %}
    </div>

    {% block content-sub %}{% endblock %}

    {% block footer %}{% endblock %}

    {% block errors %}{% endblock %}

    {% block js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/index.css">
{% endblock %}

{% block content-prev %}
    <div class="background"></div>
{% endblock %}

{% block content %}
    <div class="description">
        <div class="desc1 icon-newspaper"><a>Put your tour plain in my page</a></div>
        <div class="desc2 icon-subway"><a>Choose the station near by spot</a></div>
        <div class="desc3 icon-help"><a>Ask for a guide you want<br/>to hang out with</a></div>
        <div class="desc4 icon-attention-alt"><a>Make friends and enjoy Seoul!</a></div>
        <div class="desc5 icon-pencil"><a>Put a Review in your friend's page<br/>after travel!</a></div>
    </div>
    <div class="search">
        <a href="/travel/" class="icon-search">Any spot you interested in Seoul!</a>
    </div>
    <div class="my-page">
        <div>
            <a href="/user/" class="icon-user"></a>
        </div>
        <div>
            <a href="/logout/" class="icon-logout"></a>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/login.css">
{% endblock %}

{% block content %}
    <div class="logo">
        <img src="/static/img/logo.png" alt="logo">
    </div>
    <div class="form">
        <form action="." method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="/">
            <div class="input input-username">
                <label for="id_username">Username</label>
                <input id="id_username" maxlength="254" name="username" type="text" autofocus/>
            </div>
            <div class="input input-password">
                <label for="id_password">Password</label>
                <input id="id_password" name="password" type="password" />
            </div>
            <div class="input input-submit">
                <input type="submit" value="Login">
            </div>
        </form>
    </div>
    <div class="links">
            <a class="signup" href="/signup">Join</a>
            <a class="lost" href="/lost">Forgot Password</a>
    </div>
{% endblock %}

{% block errors %}
    {% if form.errors %}
        <script>window.onload=function() {alert("Please check your username or password and try again.");}; </script>
    {% endif %}
{% endblock %}

templates/lost.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/lost.css">
{% endblock %}

{% block nav %}
    <nav>
        <div class="container-nav">
            <div class="back"><a href="/" class="icon-angle-left"></a></div>
            <div class="title">Reset Password</div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="form">
        <form action="." method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="/">
            <div class="input input-username">
                <label for="id_username">Username</label>
                <input id="id_username" maxlength="254" name="username" type="text" />
            </div>
            <div class="input input-email">
                <label for="id_email">Email</label>
                <input id="id_email" name="email" type="email" />
            </div>
            <div class="button button-code">
                <button id="code">Send Code</button>
            </div>
            <div class="input input-cert-code">
                <label for="id_cert_code">Code</label>
                <input id="id_cert_code" maxlength="30" name="cert_code" type="text" />
            </div>
            <div class="input input-password">
                <label for="id_password">Password</label>
                <input id="id_password" maxlength="30" name="password" type="password" />
            </div>
            <div class="input input-password-check">
                <label for="id_password_check">Confirm password</label>
                <input id="id_password_check" maxlength="30" name="password_check" type="password" />
            </div>
            <div class="input input-submit">
                <input type="submit" value="Reset Password">
            </div>
        </form>
    </div>
{% endblock %}

{% block errors %}
    {% if form.username.errors %}
        <script>window.onload=function() {alert("{{ form.errors.username.0 }}");}; </script>
    {% elif form.email.errors %}
        <script>window.onload=function() {alert("{{ form.errors.email.0 }}");}; </script>
    {% elif form.password.errors %}
        <script>window.onload=function() {alert("{{ form.errors.password.0 }}");}; </script>
    {% elif form.password_check.errors %}
        <script>window.onload=function() {alert("{{ form.errors.password_check.0 }}");}; </script>
    {% elif status == 1 %}
        <script>window.onload=function() {alert("You've reset password. Please login.");}; </script>
    {% endif %}
{% endblock %}

{% block js %}
    <script src="/static/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/static/js/lost.js"></script>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/signup.css">
{% endblock %}

{% block nav %}
    <nav>
        <div class="container-nav">
            <div class="back"><a href="/" class="icon-angle-left"></a></div>
            <div class="title">Join</div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="form">
        <form method="POST">
            {% csrf_token %}
            <div class="input input-username">
                <label for="id_username">ID</label>
                <input id="id_username" maxlength="30" name="username" type="text" autofocus/>
            </div>
            <div class="input input-password">
                <label for="id_password">Password</label>
                <input id="id_password" maxlength="30" name="password" type="password" />
            </div>
            <div class="input input-password-check">
                <label for="id_password_check">Confirm password</label>
                <input id="id_password_check" maxlength="30" name="password_check" type="password" />
            </div>

            <div class="input input-email">
                <label for="id_email">Email</label>
                <input id="id_email" name="email" type="email"/>
            </div>
            <div class="input input-submit">
                <input type="submit" value="Join" />
            </div>
        </form>
    </div>
{% endblock %}

{% block errors %}
    {% if form.username.errors %}
        <script>window.onload=function() {alert("{{ form.errors.username.0 }}");}; </script>
    {% elif form.password.errors %}
        <script>window.onload=function() {alert("{{ form.errors.password.0 }}");}; </script>
    {% elif form.password_check.errors %}
        <script>window.onload=function() {alert("{{ form.errors.password_check.0 }}");}; </script>
    {% elif form.email.errors %}
        <script>window.onload=function() {alert("{{ form.errors.email.0 }}");}; </script>
    {% elif status == 1 %}
        <script>window.onload=function() {alert("You've just created an account. Login please."); location.href="/";}; </script>
    {% endif %}
{% endblock %}