user/urls.py
from django.conf.urls import patterns, url
from user.views import *


urlpatterns = patterns('',
    url(r'^$', user_info, name="user_info"),
    url(r'^match_list/$', match_list, name="match_list"),
    url(r'^match_list/(?P<match_id>\d+)/call_status/$', status, name="call_status"),
    url(r'^match_list/(?P<match_id>\d+)/receive_status/$', status, name="receive_status"),
    url(r'^match_list/(?P<match_id>\d+)/complete_status/$', status, name="complete_status"),

    url(r'^match_list/(?P<match_id>\d+)/call_status/cancel/$', cancel_guide, name="call_cancel"),
    url(r'^match_list/(?P<match_id>\d+)/receive_status/cancel/$', cancel_guide, name="receive_cancel"),

    url(r'^match_list/(?P<match_id>\d+)/receive_status/accept/$', accept_guide, name="receive_accept"),

    url(r'^match_list/(?P<match_id>\d+)/call_status/complete/$', complete_guide, name="call_complete"),
    url(r'^match_list/(?P<match_id>\d+)/receive_status/complete/$', complete_guide, name="receive_complete"),

    url(r'^match_list/(?P<match_id>\d+)/complete_status/review/$', review, name="review"),
)

user/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.template.context import Context
from django.template.loader import get_template
from travel.models import DefaultStation


class MyUser(models.Model):
    user = models.ForeignKey(User, related_name="my_user")
    profile_picture = models.ImageField(max_length=1024, upload_to='static/profile/%Y/%m/%d/%h/%m/%s', blank=True)
    gender = models.CharField(max_length=10, blank=False, default='0')
    about_me = models.TextField(max_length=500, blank=True)
    cert_code = models.CharField(max_length=20, blank=True)
    is_auth = models.BooleanField(default=False, blank=False)
    extra = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def send(self):
        subject = '인증번호'
        template = get_template('send_code.txt')
        context = Context({
            'name': self.user.username,
            'code': self.cert_code,
        })
        message = template.render(context)
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.user.email])


class Language(models.Model):
    user = models.ForeignKey(User, related_name="language")
    language = models.CharField(max_length=20)
    extra = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)


class MyStation(models.Model):
    user = models.ForeignKey(User, related_name="station_user")
    station = models.ForeignKey(DefaultStation, related_name="station_station")
    extra = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

user/forms.py
import re
from django import forms
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.forms.widgets import Textarea
from django.http.response import HttpResponseBadRequest
from rest_framework.status import HTTP_400_BAD_REQUEST
from travel.models import DefaultStation
from user.models import User

options_place = []
options_place.append((0, 'No Guide'))
for station in DefaultStation.objects.all().exclude(line__in=['E', 'G', 'I', 'S', 'SU', 'U']).order_by('station'):
    options_place.append((station.station_code, station))

options_language = []
options_language.append(('0', '한국어'))
options_language.append(('1', 'English'))
options_language.append(('2', '日本語'))
options_language.append(('3', '中国'))


options_gender = []
options_gender.append(('0', 'Man'))
options_gender.append(('1', 'Woman'))


error_message = {
    'min_max': {
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
        'max_length': 'less than %(limit_value)d characters. (current %(show_value)d)',
    },
    'about_me': {
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
        'max_length': 'less than %(limit_value)d characters. (current %(show_value)d)',
    },
    'username': {
        'required': 'Please enter ID.',
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
        'max_length': 'less than %(limit_value)d characters. (current %(show_value)d)',
    },
    'password': {
        'required': 'Please enter password',
        'min_length': 'more than %(limit_value)d characters. (current %(show_value)d)',
    },
    'placeLanguage': {
        'invalid_choice': 'Please enter correct choice.',
        'invalid_list': 'Please enter correct list.'
    },
    'email': {
        'required': 'Missing email address.',
    },
    'cert_code': {
        'required': 'Enter correct Code.'
    },
    'invalid_login': 'Please enter correct ID/ PW',
}


class Clean:
    @staticmethod
    def _username(username):
        if not re.search(r'^[A-Za-z1-9_]+$', username):
            raise forms.ValidationError('Username is Alphabet, underline(_) and Number only.')

    @staticmethod
    def exist_username(username):
        Clean._username(username)
        try:
            User.objects.get(username=username)
        except (ObjectDoesNotExist, MultipleObjectsReturned):
            return username
        raise forms.ValidationError("")

    @staticmethod
    def not_exist_username(username):
        Clean._username(username)
        try:
            User.objects.get(username=username)
        except (ObjectDoesNotExist, MultipleObjectsReturned):
            raise forms.ValidationError("User info doesn't exist.")
        return username

    @staticmethod
    def not_exist_email(email):
        try:
            User.objects.filter(email=email)
        except ObjectDoesNotExist:
            raise forms.ValidationError("User info doesn't exist.")
        return email

    @staticmethod
    def password_check(password, password_check):
        if password == password_check:
            return password_check

        raise forms.ValidationError('Check password again.')

    @staticmethod
    def name(name):
        if name != '':
            compiler = re.compile(r'^[A-Za-zㄱ-ㅣ가-힣]+')
            if compiler.findall(name):
                if name != compiler.findall(name)[0]:
                    raise forms.ValidationError('User name - Alphabet and Hangeul only.')
            else:
                raise forms.ValidationError('User name - Alphabet and Hangeul only.')
        return name

    @staticmethod
    def content(content):
        if content != '':
            compiler = re.compile(r'^[0-9A-Za-zㄱ-ㅣ가-힣]+')
            if compiler.findall(content):
                pass
            else:
                raise forms.ValidationError('Alphabet, Hangeul and Number only.')
        return content


class SendForm(forms.Form):
    username = forms.CharField(label='ID', min_length=4, max_length=30, required=True,
                               error_messages=error_message['username'])
    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])

    def clean_username(self):
        return Clean.not_exist_username(self.cleaned_data['username'])

    def clean_email(self):
        return Clean.not_exist_email(self.cleaned_data['email'])


class LostForm(forms.Form):
    username = forms.CharField(label='ID', min_length=4, max_length=30, required=True,
                               error_messages=error_message['username'])
    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])
    cert_code = forms.CharField(label='Code', max_length=30, required=True,
                                error_messages=error_message['cert_code'])
    password = forms.CharField(label="Password", min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput, error_messages=error_message['password'])
    password_check = forms.CharField(label="Password(again)", min_length=6, max_length=30, required=True,
                                     widget=forms.PasswordInput, error_messages=error_message['password'])

    def clean_username(self):
        return Clean.not_exist_username(self.cleaned_data['username'])

    def clean_email(self):
        return Clean.not_exist_email(self.cleaned_data['email'])

    def clean_password_check(self):
        return Clean.password_check(self.cleaned_data['password'], self.cleaned_data['password_check'])


class SignupForm(forms.Form):
    username = forms.CharField(label='ID', min_length=4, max_length=30, required=True,
                               error_messages=error_message['username'])
    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])
    password = forms.CharField(label="Password", min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput, error_messages=error_message['password'])
    password_check = forms.CharField(label="Password(again)", min_length=6, max_length=30, required=True,
                                     widget=forms.PasswordInput, error_messages=error_message['password'])

    def clean_password_check(self):
        return Clean.password_check(self.cleaned_data['password'], self.cleaned_data['password_check'])

    def clean_username(self):
        return Clean.exist_username(self.cleaned_data['username'])


class UserInfoForm(forms.Form):
    profile_picture = forms.ImageField(widget=forms.FileInput, required=False)
    first_name = forms.CharField(label="First_Name", min_length=1, max_length=30, required=False,
                                 error_messages=error_message['min_max'])
    last_name = forms.CharField(label="Last_Name", min_length=1, max_length=30, required=False,
                                error_messages=error_message['min_max'])
    gender = forms.ChoiceField(label='Gender', choices=options_gender, required=False)
    place = forms.MultipleChoiceField(label='Place', widget=forms.SelectMultiple, choices=options_place,
                                      required=False, error_messages=error_message['placeLanguage'])
    language = forms.MultipleChoiceField(label='Language', widget=forms.SelectMultiple, choices=options_language,
                                         required=False, error_messages=error_message['placeLanguage'])
    about_me = forms.CharField(label='About_Me', max_length=300, required=False,
                               widget=Textarea, error_messages=error_message['about_me'])

    email = forms.EmailField(label="Email", required=True,
                             widget=forms.EmailInput, error_messages=error_message['email'])
    password = forms.CharField(label="Password(current)", min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput, error_messages=error_message['password'])
    change_password = forms.CharField(label="Password(change)", min_length=6, max_length=30, required=False,
                                      widget=forms.PasswordInput, error_messages=error_message['password'])
    change_password_check = forms.CharField(label="Password(change again)", min_length=6, max_length=30,
                                            required=False, widget=forms.PasswordInput,
                                            error_messages=error_message['password'])

    def clean_first_name(self):
        return Clean.name(self.cleaned_data['first_name'])

    def clean_last_name(self):
        return Clean.name(self.cleaned_data['last_name'])

    def clean_change_password_check(self):
        return Clean.password_check(self.cleaned_data['change_password'], self.cleaned_data['change_password_check'])


class ReviewForm(forms.Form):
    content = forms.CharField(label='About_Me', min_length=1, max_length=300, required=True,
                              widget=Textarea, error_messages=error_message['about_me'])

    def clean_content(self):
        return Clean.content(self.cleaned_data['content'])

templates/user/comment.html
<!DOCTYPE HTML>
<!--//
This web page has been developed by J.
 - jicjjang12@gmail.com
-->
<html lang="ko">
<head>
    <title>Show me the Seoul</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="shortcut icon" type="image/ico" href="/static/img/favicon.ico" />

    <!--[if lt IE 9]>
    <script src="/static/vendor/html5shiv/dist/html5shiv.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="/static/css/user/user.css">

    <!--[if lt IE 9]>
    <script src="/static/vendor/respond/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="guide">
        {% if user_list.1.profile_picture %}
            <div class="profile_picture">
                <img src="/{{ user_list.1.profile_picture }}" alt="profile_picture" />
            </div>
        {% else %}
            <div class="profile_picture">
                <img src="/{{ default_picture }}" alt="default_picture" />
            </div>
        {% endif %}
        <div class="username">{{ user_list.0.username }}</div>
        <div class="first_name">{% if user_list.0.first_name %}{{ user_list.0.first_name }}{% endif %}</div>
        <div class="last_name">{% if user_list.0.last_name %}{{ user_list.0.last_name }}{% endif %}</div>
        <div class="gender">{% if user_list.1.gender %}
            {% if user_list.1.gender == 0 %}남자
            {% elif user_list.1.gender == 1 %}여자
            {% endif %}{% endif %}
        </div>
        <div class="place">
            {% if places %}{% for place in places %}
                <a>Line {{place.station.line}}, {{ place.station.station }}역</a>
            {% endfor %}{% endif %}
        </div>
        <div class="languages">
            {% if languages %}{% for language in languages %}{% if language.language == '0' %}
                <a>한국어</a>
            {% elif language.language == '1' %}
                <a>English</a>
            {% elif language.language == '2' %}
                <a>日本語</a>
            {% elif language.language == '3' %}
                <a>中国</a>
            {% endif %}{% endfor %}{% endif %}
        </div>
        <div class="about_me">{% if user_list.1.about_me %}{{ user_list.1.about_me }}{% endif %}</div>
        <div class="email">{% if user_list.0.email %}{{ user_list.0.email }}{% endif %}</div>
    </div>
    <div class="ask">
    {% csrf_token %}
        {% if status == 'invite' %}
            <div>아직 상대가 확인 안눌렀어요. 기다려요</div>
            <button class="cancel">취소해요</button>
        {% endif %}
        {% if status == 'receive' %}
            <button class="accept">초대 받았네요. 초대에 응하세요!</button>
            <button class="cancel">야 꺼져</button>
        {% endif %}
        {% if status == 'confirm' %}
            <div>여행을 떠나세요!</div>
            <button class="complete">여행이 끝나면 눌러주세요.</button>
        {% endif %}
        {% if status == 'complete' %}
            <div>종료된 여행이에요...</div>
            <button class="review">리뷰를 작성해주세요</button>
        {% endif %}
    </div>
    <script src="/static/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/static/js/user/match.js"></script>
</body>
</html>

templates/user/match.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/user/match.css">
{% endblock %}

{% block nav %}
    <nav>
        <div class="container-nav">
            <div class="back"><a href="/user/match_list/" class="icon-angle-left"></a></div>
            <div class="title">Matching</div>
            <div class="title-review inactive">Write a review</div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="user">
        {% if user_list.1.profile_picture %}
            <div class="profile-picture">
                <img src="/{{ user_list.1.profile_picture }}" alt="profile_picture" />
            </div>
        {% else %}
            <div class="profile-picture">
                <img src="/{{ default_picture }}" alt="default_picture" />
            </div>
        {% endif %}
        <label for="first-name">First Name</label>
        <div id="first-name" class="input first-name">{% if user_list.0.first_name %}{{ user_list.0.first_name }}{% endif %}</div>
        <label for="last-name">Last Name</label>
        <div id="last-name" class="input last-name">{% if user_list.0.last_name %}{{ user_list.0.last_name }}{% endif %}</div>
        <label for="gender">Gender</label>
        <div id="gender" class="input gender">{% if user_list.1.gender %}
            {% if user_list.1.gender == '0' %}남자
            {% elif user_list.1.gender == '1' %}여자
            {% endif %}{% endif %}
        </div>
        <label for="place">Place</label>
        <div id="place" class="select place">
            {% if places %}{% for place in places %}
                <a>Line {{place.station.line}}, {{ place.station.station }}역</a>
            {% endfor %}{% endif %}
        </div>
        <label for="languages">Languages</label>
        <div id="languages" class="select languages">
            {% if languages %}{% for language in languages %}{% if language.language == '0' %}
                <a>한국어</a>
            {% elif language.language == '1' %}
                <a>English</a>
            {% elif language.language == '2' %}
                <a>日本語</a>
            {% elif language.language == '3' %}
                <a>中国</a>
            {% endif %}{% endfor %}{% endif %}
        </div>
        <label for="about-me">About Me</label>
        <div id="about-me" class="textarea about-me">{% if user_list.1.about_me %}{{ user_list.1.about_me }}{% endif %}</div>
        <label for="email">Email</label>
        <div id="email" class="input email">{% if user_list.0.email %}{{ user_list.0.email }}{% endif %}</div>
    </div>
    <div id="ask" class="ask">
    {% csrf_token %}
        {% if status == 'invite' %}
            <button class="cancel">Cancel request.</button>
        {% endif %}
        {% if status == 'receive' %}
            <div class="receive">
                <button class="cancel">Cancel request.</button>
                <button class="accept">Ask for a guide.</button>
            </div>
        {% endif %}
        {% if status == 'confirm' %}
            <button class="complete">We had been travelled!</button>
        {% endif %}
        {% if status == 'complete' %}
            <button class="review">Write a review.</button>
        {% endif %}
    </div>
{% endblock %}

{% block content-sub %}
    {% if status == 'complete' %}
        <div class="container container-sub inactive">
            <form method="POST">
                {% csrf_token %}
                <div class="textarea textarea-content">
                    <label for="id_content">About Me</label>
                    <textarea id="id_content" maxlength="300" name="content" cols="40"
                              rows="10">{{ comment.content }}</textarea>
                </div>
                <div class="input ask">
                    <button class="later">Later</button>
                </div>
                <div class="input input-submit">
                    <input class="comment-submit" type="submit" value="Save"/>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

{% block footer %}
    <footer>
        <div class="home"><a class="icon-home" href="/"></a></div>
        <div class="user"><a class="icon-user" href="/user/"></a></div>
        <div class="users"><a class="icon-users" href="/user/match_list/"></a></div>
    </footer>
{% endblock %}

{% block js %}
    <script src="/static/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/static/js/user/match.js"></script>
{% endblock %}

templates/user/match_list.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/user/match_list.css">
{% endblock %}

{% block nav %}
    <nav>
        <div class="container-nav">
            <div class="back"><a href="/user/" class="icon-angle-left"></a></div>
            <div class="title">Matching</div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="guide_status">
        <div class="call"><a>Asking</a></div>
        <div class="receive active"><a>Waiting for<br/>your reply!</a></div>
        <div class="complete"><a>Matched</a></div>
    </div>
    <div class="guides guides-call">
        {% for call in calls %}
            <div class="guide" data-target="{{ call.0.id }}/call_status/">
                <div class="profile-picture">
                    <img src="/{{ call.1.profile_picture }}" alt="image">
                </div>
                <div class="date">{{ call.0.created|date:"Y / M / d" }}</div>
                <div class="username">{{ call.0.to_user.first_name }}, {{ call.0.to_user.last_name }}</div>
                <div class="station">{% for station in call.2 %}{{ station.station.station }} {% endfor %}</div>
                <div class="content">{{ call.1.about_me }}</div>
                <div class="comment icon-comment">{{ call.3 }}</div>
            </div>
        {% endfor %}
    </div>
    <div class="guides guides-receive active">
        {% for receive in receives %}
            <div class="guide" data-target="{{ receive.0.id }}/receive_status/">
                <div class="profile-picture">
                    <img src="/{{ receive.1.profile_picture }}" />
                </div>
                <div class="date">{{ receive.0.created|date:"Y / M / d" }}</div>
                <div class="username">{{ receive.0.from_user.first_name }}, {{ receive.0.from_user.last_name }}</div>
                <div class="station">{% for station in receive.2 %}{{ station.station.station }} {% endfor %}</div>
                <div class="content">{{ receive.1.about_me }}</div>
                <div class="comment icon-comment">{{ receive.3 }}</div>
            </div>
        {% endfor %}
    </div>
    <div class="guides guides-complete">
        {% for before_travel in before_travels1 %}
            <div class="guide" data-target="{{ before_travel.0.id }}/complete_status/">
                <div class="profile-picture">
                    <img src="/{{ before_travel.1.profile_picture }}" />
                </div>
                <div class="date">{{ before_travel.0.created|date:"Y / M / d" }}</div>
                <div class="username">{{ before_travel.0.to_user.first_name }}, {{ before_travel.0.to_user.last_name }}</div>
                <div class="station">{% for station in before_travel.2 %}{{ station.station.station }} {% endfor %}</div>
                <div class="content">{{ before_travel.1.about_me }}</div>
                <div class="comment icon-comment">{{ before_travel.3 }}</div>
            </div>
        {% endfor %}
        {% for before_travel in before_travels2 %}
            <div class="guide" data-target="{{ before_travel.0.id }}/complete_status/">
                <div class="profile-picture">
                    <img src="/{{ before_travel.1.profile_picture }}" />
                </div>
                <div class="date">{{ before_travel.0.created|date:"Y / M / d" }}</div>
                <div class="username">{{ before_travel.0.to_user.first_name }}, {{ before_travel.0.to_user.last_name }}</div>
                <div class="station">{% for station in before_travel.2 %}{{ station.station.station }} {% endfor %}</div>
                <div class="content">{{ before_travel.1.about_me }}</div>
                <div class="comment icon-comment">{{ before_travel.3 }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block footer %}
    <footer>
        <div class="home"><a class="icon-home" href="/"></a></div>
        <div class="user"><a class="icon-user" href="/user/"></a></div>
        <div class="users"><a class="icon-users" href="/user/match_list/"></a></div>
    </footer>
{% endblock %}

{% block js %}
    <script src="/static/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/static/js/user/match_list.js"></script>
{% endblock %}

templates/user/user.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/user/user.css">
{% endblock %}

{% block nav %}
    <nav>
        <div class="container-nav">
            <div class="back"><a href="/" class="icon-angle-left"></a></div>
            <div class="title">My page</div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="form">
        <form action="." enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {% if user_list.1.profile_picture %}
                <div class="profile-picture">
                    <img src="/{{ user_list.1.profile_picture }}" alt="profile_picture" />
                    <a class="icon-check-empty-after">Del</a>
                    <a class="icon-camera"></a>
                </div>
                <div class="input input-profile-delete">
                    <input id="id_profile_delete" type="checkbox" name="picture_delete" value="1"/>
                </div>
            {% else %}
                <div class="profile-picture">
                    <img src="/{{ default_picture }}" alt="default_picture" />
                    <a class="icon-camera"></a>
                </div>
            {% endif %}
            <div class="input input-profile-picture">
                <input id="id_profile_picture" name="profile_picture" onChange="changeImage(this)"type="file"/>
            </div>
            <div class="input input-first-name">
                <label for="id_first_name">First Name</label>
                <input id="id_first_name" maxlength="30" name="first_name" type="text"
                       {% if user_list.0.first_name %}value="{{ user_list.0.first_name }}"{% endif %}/>
            </div>
            <div class="input input-last-name">
                <label for="id_last_name">Last Name</label>
                <input id="id_last_name" maxlength="30" name="last_name" type="text"
                       {% if user_list.0.last_name %}value="{{ user_list.0.last_name }}"{% endif %}/>
            </div>
            <div class="input input-gender">
                <label for="id_gender">Gender</label>
                <select id="id_gender" name="gender">
                    {% for k, v in form.fields.gender.choices %}
                        <option value="{{ k }}"{% if user_list.1.gender == k %}selected{% endif %}>{{ v }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input input-place">
                <label for="id_place">Place</label>
                <select multiple="multiple" id="id_place" name="place">
                    {% for k, v in form.fields.place.choices %}
                        <option value="{{ k }}"{% for place in places %}
                                {% if place.station.station_code == k %}selected{% endif %}
                        {% endfor %}>{% if k == 0 %}{{ v }}{% else %}Line{{ v.line }}, {{ v.station }}{% endif %}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input input-language">
                <label for="id_language">Language</label>
                <select multiple="multiple" id="id_language" name="language">
                    {% for k, v in form.fields.language.choices %}
                        <option value="{{ k }}"{% for language in languages %}{% if language.language == k %}selected{% endif %}{% endfor %}>{{ v }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input input-about-me">
                <label for="id_about_me">About Me</label>
                <textarea cols="40" id="id_about_me" maxlength="300" name="about_me"
                          rows="10">{% if user_list.1.about_me %}{{ user_list.1.about_me }}{% endif %}</textarea>
            </div>
            <div class="input input-email">
                <label for="id_email">Email</label>
                <input id="id_email" name="email" type="email"
                       value="{% if user_list.0.email %}{{ user_list.0.email }}{% endif %}"/>
            </div>
            <div class="input input-password">
                <label for="id_password">Password</label>
                <input id="id_password" maxlength="30" name="password" type="password" />
            </div>
            <div class="input input-change-password">
                <label for="id_change_password">Change Password</label>
                <input id="id_change_password" maxlength="30" name="change_password" type="password" />
            </div>
            <div class="input input-change-password-check">
                <label for="id_change_password_check">Confirm Password</label>
                <input id="id_change_password_check" maxlength="30" name="change_password_check" type="password" />
            </div>
            <div class="input input-submit">
                <input type="submit" value="Save" />
            </div>
        </form>
    </div>
{% endblock %}

{% block content-sub %}
    <div class="container container-sub">
        {% if comment_list %}
            {% for comment in comment_list %}
                <div class="guide">
                    <div class="profile-picture">
                        <img src="/{{ comment.2.profile_picture }}" alt="image">
                    </div>
                    <div class="date">{{ comment.0.created|date:"Y / M / d" }}</div>
                    <div class="username">{{ comment.1.username }}</div>
                    <div class="content">{{ comment.0.content }}</div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

{% block footer %}
    <footer>
        <div class="home"><a class="icon-home" href="/"></a></div>
        <div class="user"><a class="icon-user" href="/user/"></a></div>
        <div class="users"><a class="icon-users" href="/user/match_list/"></a></div>
    </footer>
{% endblock %}

{% block errors %}
    {% if form.first_name.errors %}
        <script>window.onload=function() {alert("{{ form.errors.first_name.0 }}");}; </script>
    {% elif form.last_name.errors %}
        <script>window.onload=function() {alert("{{ form.errors.last_name.0 }}");}; </script>
    {% elif form.gender.errors %}
        <script>window.onload=function() {alert("{{ form.errors.gender.0 }}");}; </script>
    {% elif form.place.errors %}
        <script>window.onload=function() {alert("{{ form.errors.place.0 }}");}; </script>
    {% elif form.language.errors %}
        <script>window.onload=function() {alert("{{ form.errors.language.0 }}");}; </script>
    {% elif form.about_me.errors %}
        <script>window.onload=function() {alert("{{ form.errors.about_me.0 }}");}; </script>
    {% elif form.password.errors %}
        <script>window.onload=function() {alert("{{ form.errors.password.0 }}");}; </script>
    {% elif form.change_password.errors %}
        <script>window.onload=function() {alert("{{ form.errors.change_password.0 }}");}; </script>
    {% elif form.change_password_check.errors %}
        <script>window.onload=function() {alert("{{ form.errors.change_password_check.0 }}");}; </script>
    {% elif status == 1 %}
        <script>window.onload=function() {alert("You've changed information!");}; </script>
    {% endif %}
{% endblock %}

{% block js %}
    <script src="/static/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/static/js/user/user.js"></script>
{% endblock %}